branches:
  only:
    - master
dist: trusty
language: python
python:
  - '3.6'
install: true
before_script:
  - pip install pygithub;
  - pip install pygithub3;
  - pip install sqflint;
script:
  - python3 tools/sqf_validator.py
  - python3 tools/config_style_checker.py
  - python3 tools/search_privates.py
  - python3 tools/sqf_linter.py
  - python3 tools/search_unused_privates.py
notifications:
  email:
    on_success: never
    on_failure: change
