name = "Neviothr's Mod Pack";
picture = "\nev_debugMenu\logo.paa";
logoSmall = "\nev_debugMenu\logo.paa";
logo = "\nev_debugMenu\logo.paa";
logoOver = "\nev_debugMenu\logo.paa";
action = "https://github.com/Neviothr/ArmA";
tooltipOwned = "Neviothr's addons";
dlcColor[] = {1, 0.706, 0.075, 1};
overview = "Neviothr's addons. A collection of addons designed to improve gameplay.";
hideName = 0
hidePicture = 0;